[build]
  command = "SKIP_PREFLIGHT_CHECK=true npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/api/*"
  to = "https://trading-dashboard-backend-qwe4.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"