# Render Deployment Configuration

services:
  - type: web
    name: lakshya-trading-frontend
    env: node
    region: singapore # Change this to your preferred region
    buildCommand: npm install && npm run build && cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true